/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _POSINT_H_RPCGEN
#define _POSINT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct insert_args {
	int new_element;
	int index;
};
typedef struct insert_args insert_args;

#define POS_INT_PROG 0x2cc73fb9
#define POS_INT_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define INSERT 1
extern  int * insert_1(insert_args *, CLIENT *);
extern  int * insert_1_svc(insert_args *, struct svc_req *);
#define RETRIEVE 2
extern  int * retrieve_1(int *, CLIENT *);
extern  int * retrieve_1_svc(int *, struct svc_req *);
#define DELETE 3
extern  int * delete_1(int *, CLIENT *);
extern  int * delete_1_svc(int *, struct svc_req *);
extern int pos_int_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define INSERT 1
extern  int * insert_1();
extern  int * insert_1_svc();
#define RETRIEVE 2
extern  int * retrieve_1();
extern  int * retrieve_1_svc();
#define DELETE 3
extern  int * delete_1();
extern  int * delete_1_svc();
extern int pos_int_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_insert_args (XDR *, insert_args*);

#else /* K&R C */
extern bool_t xdr_insert_args ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_POSINT_H_RPCGEN */
